on:
  workflow_dispatch:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  tag-major:
    name: Push major-release
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false